### ISSUE TITLE
Make one libgit2 example work from Winxed

### ISSUE THREAD

**Issue by leto** [letolabs/parrot-libgit2#15]
This will involve adding a few high-level Winxed bindings to already-existing lower-level PIR bindings. Syntax sugar :cookie:

This will also be essential as an example that new developers can understand, tweak and learn from.

**Comment by sa1** [comment]
Potential examples are:
1) http://libgit2.github.com/libgit2/ex/HEAD/showindex.html
2) http://libgit2.github.com/libgit2/ex/HEAD/general.html
3) http://libgit2.github.com/libgit2/ex/HEAD/rev-list.html
4) http://libgit2.github.com/libgit2/ex/HEAD/diff.html

The showindex example would be the first thing that I'll try and add.
