### ISSUE TITLE
Tests do not work on case-insensitive filesystems

### ISSUE THREAD

**Issue by leto** [letolabs/parrot-libgit2#17]
Yes, case insensitive filesystems are an ABOMINATION, but most OS X machines have that as a default:

```
ln -s Rosella/rosella rosella
ln: rosella/rosella: File exists
make: *** [rosella] Error 1
```

We try to use a directory called rosella and Rosella in the root of parrot-libgit2.git, which fails. We should be using ext/Rosella

**Comment by sa1** [comment]
okay, will fix this. Lots of things are already platform specific, but we
can still support OS X.
